sudo: required
dist: trusty
language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: jonas.birme@eyevinn.se
  api_key:
    secure: FvWeY9Dxk1f3NILMjK7lTe19bOwcos4hCRWaptuyVonjD26zMnpCng+6jr+zKvroAW1tDuTdGE/gudsLgbYZx4VrDs9qFTst+p/ML9cpAIx3prENzOA9NEQmDi9BtHUa/AJUcosezVthm8ZNY1CdFMcBPv7H8Cvdain6CGgPZfKyMx2az3L6w6muZX8z0/mwWpTl3uvnW5Pey8Kx4UrUnKD+IXuj+yg1kVYsrCRoigQqwNPbs5E667r/us6Xpm8IYYTA9PwKnRJOcnf7Bg4PPvPyUboNcRB8SdjTKdgAK3EpDFLpl/8IiwJSl8Hk25Bwe1YBtPjKYtc052gqWjaPynJPFp9uyCTzNp8nhaodt0TouD6kdtnFtdpWOQlcMhvp7CLI26ycl1EmtKzcenAQVXarT+EfC6CirZxM7qRxG2wuMVY+/sjq/SlWSi9PbwD3NlcMN0rUkjVJrEoYdU9MmF8uMu30PKBmPWWdq9QBTPzwAC/rEqHyxAGdV9uH/j2LOHYb2ZI6pL4aqUajnqjrrlkrF7z7DbQWxATkLGV9E3aUxQe/36xS/EKEiYxSdTVgFkL0k6e7eN/SL0DzuioPiJDys2W0YCBrgINkz5hzvdsvzfpJrV1rTMTVkfPG+jziBUXVezpRAh0Zl73pLVNhSIxQ8yLFkhCoZQLGGx3dXPY=
  on:
    tags: true
    repo: Eyevinn/vod-to-live.js
