sudo: required
dist: trusty
language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: jonas.birme@eyevinn.se
  api_key:
    secure: jo3W8wUv30eII2ankrQ9E4TUV1d9HuEVBytIDWM4HBYTM1S0YZYqagbiEe1GDIy03UKx0FJiclmC3TKLcQedT+6VR35m5WK04VIR1jbOI+n1xAsocHxt8jvGEwdIofUSDQ2FZJOP/GjMMgeZ98i4sTYVw4jgc9+UjbaYOzVUtF6gNauGBHSzLiDp/l165MPiBFbQkzLf4zjj6Ul4Pw0TRmMivPS2dJvj9d+fTLmp3a7GulVSEpARpfcjFePAfTA22B3EXuyiAGfgYDJTwGhURYRl43nqIkJj700B+wvWgj2DQlSotyB5U8QakxYwgFvyVY80Uq1lJ9KVVvYq6cHDnxGLcT578lBeYj2s/FVUkdcET4WWACsp2jU5ttuA33J/ov2E/dCo9H4+SmMuNulnG0p6KBM6TPXCx9m62T9c3tK7b/YmNpVWAJdKlysaF0cm+BeiqXhuTsbR4Wgb1TCx9sBRqo16QQiRzGdqwHB3oOoNapLRyBG0MO7P43lk6HMjhgBTr6FfHxTHanO+MJgNRPbSq/473McIfw1RnYippAPLJ5ABpbN33bRtIHohPO5uyb/SfB4U6sHDpIhL+nURVgAzsar5Z71afCE4uXuzPJYgVvGcoQ1Em7VV/Acljud/hB8CK4EfDUgOVcUwvb2Qn15jNeBswLHGKhhZM1hNGJ0=
  on:
    tags: true
    repo: Eyevinn/vod-to-live.js

