sudo: required
dist: trusty
language: node_js
node_js:
  - '6'
deploy:
  provider: npm
  email: jonas.birme@eyevinn.se
  api_key:
    secure: WcQXYjnDdly1GS61RVIeYgxRvirn3nMpt5Yw73rommrm5WjC4yz1CfM3qFDE2pQHllLKrLn+g9+vZamFZPr5mOoOgx0y0AfaVO2ee+vBWXiAC7yQwXs3R/+uHP29TRLXf4NG//Qetg3Yjz+EBfwpZ6qhZKpanEI5FzEKGoIfVVP46HGEmKOVZ3hma0KA+I/FawIPC3FyhAGeySijnBWGnHtiU2wU3aT9uNuixWqissFgT677CvIRbi8IHCQp57LNf9xemovHlrPSP0kaWXgPII7DJB05lu+gZE6KpwO92DAs2BbKrmr8Ofl42+jTgJkWKInHvqZacx9Ygv2XgyImEFlSgK/ExA/NpCRZvW3kpHAdAgRJLK+sn+rqjcx/hemA7d+zOUQdTR5bzFy40/g5aMs6VFBvfrjwn4UX2vTCaZ/LBOvlnAeeeON7G0029nSF7zQJ0bxLczhmOmi39Lpngu7T7R4S/vr3ZHm2JtLfVsEGd/IxUBJgpuCyxmsDAQneh68NrTH9n+3VHMn8/4RvHw5wg4yg9/xFsG5kSCSzaAFiWYvyWn1csIO9eHgchTld5vkMz9tMk94wd/7nRek3VWXGFAbxGAog0QpDaub8D+26b9qAmgtBkKLPD+p/hcs6fc7un/JizcWzfeeKxXjPA16hz9KFPMO9MZNsow5lXxo=
  on:
    tags: true
    repo: Eyevinn/vod-to-live.js

